[package]
name = "example"
version = "0.1.0"
authors = ["Oscar Beaumont <oscar@otbeaumont.me>"]
edition = "2018"

[dependencies]
tracing = "0.1.26"
tracing-subscriber = "0.2.18"
actix-web = "3.3.2"
tracing-actix-web2 = { path = "../" }